"""The configuration axes to sweep, and the passes that cover them.

Running one *pass* means building and executing a whole :class:`MainWorkflow`
over the phantom exam with one coherent configuration. Because a single pass
already exercises every loaded input at once, the ~50 construction scenarios of
``nipype_pipeline/matrix`` do **not** need ~50 executions: they need a small
covering set in which every value of every axis appears at least once.

Two levers keep that set small:

* **axes that live on different inputs are swept in parallel** inside one pass
  (the resting-state MELODIC dimensionality has nothing to do with the vein
  detection mode, so they can differ in the same run);
* **each pass declares which inputs it loads**, so a pass that exists to sweep
  the diffusion axes does not also re-run the (slow, already covered) fMRI
  chain.

The passes are written out explicitly rather than generated by an algorithm:
they are meant to be read and reviewed. What *is* automatic is the guarantee
that they are complete — :func:`coverage` walks every axis value and reports
any that no enabled pass exercises, so a forgotten value shows up as a hole
instead of silently disappearing. Values that require something the host does
not have are reported as *skipped, with the reason*, never as covered.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from swane.config.config_enums import (
    BlockDesign,
    CoreLimit,
    FreesurferStep,
    GlobalPrefCategoryList,
    RegistrationEngine,
    SliceTiming,
    VeinDetectionMode,
)
from swane.utils.DataInputList import DataInputList as DIL

#: Axis scopes.
GLOBAL = "global"  # a global application preference
SUBJECT = "subject"  # a per-input workflow preference
SHAPE = "shape"  # not a preference: changes which DICOM folders are wired


@dataclass(frozen=True)
class Axis:
    """One configuration dimension the sweep must cover.

    ``values`` are stored exactly as they are written into the config (strings,
    or ``Enum.name``), so a pass definition reads like the settings dialog.
    ``gates`` maps a value to the host capability it needs; a value whose gate
    is missing is dropped from the plan with that reason attached.
    ``needs_input`` records which input must be loaded for the axis to mean
    anything, so coverage is only claimed by passes that actually load it.
    """

    name: str
    scope: str
    values: tuple
    section: object = None  # GlobalPrefCategoryList / DataInputList member
    option: str = ""
    gates: dict = field(default_factory=dict)
    needs_input: object = None  # DataInputList member, or None for global
    note: str = ""

    def gate_for(self, value) -> str:
        return self.gates.get(value, "")


def _enum_values(enum_cls, *members) -> tuple:
    return tuple(getattr(enum_cls, m).name for m in members)


# --------------------------------------------------------------------------- #
# The axes
# --------------------------------------------------------------------------- #
# Kept deliberately close to the snapshot matrix in
# swane/tests/nipype_pipeline/matrix/: the same dimensions, now executed.
AXES = (
    # ---- global: tools and resources --------------------------------------
    Axis(
        name="freesurfer_step",
        scope=SUBJECT,
        section=DIL.T13D,
        option="freesurfer_step",
        values=_enum_values(
            FreesurferStep, "DISABLED", "SYNTHSEG", "AUTORECON_PIAL", "RECONALL"
        ),
        gates={
            # SynthSeg ships with the same recent-FreeSurfer "Synth" bundle as
            # SynthStrip/SynthMorph (capabilities.py), and needs the same RAM
            # floor as SynthMorph (14 GB linux / 30 GB mac, see
            # ResourceManager.synth_seg_ram_requirements) -- "freesurfer" alone
            # (just presence, >=7.3.2) does not capture either requirement.
            "SYNTHSEG": "synth_seg",
            "AUTORECON_PIAL": "freesurfer",
            "RECONALL": "freesurfer",
        },
        note="SYNTHSEG gives parcellation only; the recon-all variants are opt-in",
    ),
    Axis(
        name="hippo_amyg_labels",
        scope=SUBJECT,
        section=DIL.T13D,
        option="hippo_amyg_labels",
        values=("false", "true"),
        gates={"true": "freesurfer_matlab"},
        note="only meaningful together with RECONALL",
    ),
    Axis(
        name="synth_strip",
        scope=GLOBAL,
        section=GlobalPrefCategoryList.SYNTH,
        option="strip",
        values=("false", "true"),
        gates={"true": "synth_strip"},
    ),
    # The registration backend is an ENUM, not the old boolean ``morph`` key
    # Group A removed. FSL (FLIRT/FNIRT) is always available; SYNTH (SynthMorph)
    # and ANTS (antspyx) are each gated on their own dependency + RAM floor, so
    # a host missing one still exercises the others.
    Axis(
        name="registration_engine",
        scope=GLOBAL,
        section=GlobalPrefCategoryList.SYNTH,
        option="engine",
        values=_enum_values(RegistrationEngine, "FSL", "SYNTH", "ANTS"),
        gates={"SYNTH": "synth_morph", "ANTS": "antspyx"},
    ),
    Axis(
        name="synth_reconall",
        scope=GLOBAL,
        section=GlobalPrefCategoryList.SYNTH,
        option="reconall",
        values=("false", "true"),
        gates={"true": "synth_reconall"},
    ),
    Axis(
        name="cuda",
        scope=GLOBAL,
        section=GlobalPrefCategoryList.PERFORMANCE,
        option="cuda",
        values=("false", "true"),
        gates={"true": "cuda"},
        note="MainWorkflow propagates this into the DTI 'cuda' preference",
    ),
    Axis(
        name="multicore_node_limit",
        scope=GLOBAL,
        section=GlobalPrefCategoryList.PERFORMANCE,
        option="multicore_node_limit",
        values=_enum_values(CoreLimit, "SOFT_CAP", "HARD_CAP", "NO_LIMIT"),
    ),
    # ---- structural reference and linear registration ----------------------
    Axis(
        name="ref_bet_bias_correction",
        scope=SUBJECT,
        section=DIL.T13D,
        option="bet_bias_correction",
        values=("false", "true"),
        needs_input=DIL.T13D,
    ),
    Axis(
        name="ref_bet_thr",
        scope=SUBJECT,
        section=DIL.T13D,
        option="bet_thr",
        values=("0.3", "0.5"),
        needs_input=DIL.T13D,
    ),
    Axis(
        name="flat1",
        scope=SUBJECT,
        section=DIL.T13D,
        option="flat1",
        values=("true", "false"),
        gates={"true": "mni_templates"},
        needs_input=DIL.FLAIR3D,
        note="FLAT1 needs 3D FLAIR and the MNI template",
    ),
    # ---- functional maps (ASL / PET) ---------------------------------------
    Axis(
        name="asl_ai",
        scope=SUBJECT,
        section=DIL.ASL,
        option="ai",
        values=("false", "true"),
        gates={"true": "mni_templates"},
        needs_input=DIL.ASL,
        note="the asymmetry index needs the symmetric-atlas nonlinear registration",
    ),
    Axis(
        name="pet_ai",
        scope=SUBJECT,
        section=DIL.PET,
        option="ai",
        values=("false", "true"),
        gates={"true": "mni_templates"},
        needs_input=DIL.PET,
    ),
    # ---- venous MR ----------------------------------------------------------
    Axis(
        name="venous_mr_shape",
        scope=SHAPE,
        values=("single_series", "two_series"),
        needs_input=DIL.VENOUS_MR,
        note="one 2-volume series (split in time) vs two 1-volume series (merged)",
    ),
    Axis(
        name="vein_detection_mode",
        scope=SUBJECT,
        section=DIL.VENOUS_MR,
        option="vein_detection_mode",
        # Only the two automatic statistics that actually run image analysis are
        # exercised end to end: KURTOSIS (the default) on the single 2-volume
        # series and SD on the two-series shape, each graded on vein
        # localization. FIRST/SECOND/MEAN do not change execution -- they only
        # relabel which of the two volumes is the venous phase -- so their graph
        # coverage lives in the construction-only matrix snapshots
        # (single_series_first.txt et al.) and the VenousCheck unit tests, not in
        # this hours-long execution sweep.
        values=_enum_values(VeinDetectionMode, "KURTOSIS", "SD"),
        needs_input=DIL.VENOUS_MR,
    ),
    Axis(
        name="venous_mr_bet_thr",
        scope=SUBJECT,
        section=DIL.VENOUS_MR,
        option="bet_thr",
        values=("0.4", "0.25"),
        needs_input=DIL.VENOUS_MR,
    ),
    # ---- venous CT ----------------------------------------------------------
    Axis(
        name="venous_ct_contrasts",
        scope=SHAPE,
        values=("1", "2"),
        gates={"1": "slicer", "2": "slicer"},
        needs_input=DIL.VENOUS_CT,
        note="baseline + 1 or 2 contrast phases, summed by the workflow",
    ),
    Axis(
        name="skull_threshold",
        scope=SUBJECT,
        section=DIL.VENOUS_CT,
        option="skull_threshold",
        values=("-1", "1500"),
        gates={"-1": "slicer", "1500": "slicer"},
        needs_input=DIL.VENOUS_CT,
        note="-1 selects the automatic threshold",
    ),
    # ---- SEEG CT ------------------------------------------------------------
    Axis(
        name="electrode_threshold",
        scope=SUBJECT,
        section=DIL.SEEG_CT,
        option="electrode_threshold",
        values=("2000", "2500"),
        needs_input=DIL.SEEG_CT,
    ),
    Axis(
        name="erode_kernel_size",
        scope=SUBJECT,
        section=DIL.SEEG_CT,
        option="erode_kernel_size",
        values=("5", "8"),
        needs_input=DIL.SEEG_CT,
    ),
    # ---- diffusion -----------------------------------------------------------
    Axis(
        name="old_eddy_correct",
        scope=SUBJECT,
        section=DIL.DTI,
        option="old_eddy_correct",
        values=("false", "true"),
        needs_input=DIL.DTI,
    ),
    Axis(
        name="tractography",
        scope=SUBJECT,
        section=DIL.DTI,
        option="tractography",
        values=("false", "true"),
        gates={"true": "xtract"},
        needs_input=DIL.DTI,
        note="the sweep only enables the corticospinal tract",
    ),
    # ---- task fMRI -----------------------------------------------------------
    # The phantom generates fmri_0 as rArA and fmri_1 as rArBrArB, so a pass
    # loading both covers the whole block-design axis in one run. The
    # configuration must match the data, hence these are pinned, not swept.
    Axis(
        name="fmri0_block_design",
        scope=SUBJECT,
        section=DIL.FMRI_0,
        option="block_design",
        values=(BlockDesign.RARA.name,),
        needs_input=DIL.FMRI_0,
        note="pinned: the phantom's fmri_0 run is rArA",
    ),
    Axis(
        name="fmri1_block_design",
        scope=SUBJECT,
        section=DIL.FMRI_1,
        option="block_design",
        values=(BlockDesign.RARB.name,),
        needs_input=DIL.FMRI_1,
        note="pinned: the phantom's fmri_1 run is rArBrArB",
    ),
    # Slice timing is a pure preference (the phantom writes no slice-timing
    # tags), so the two task runs can carry different values in the same pass.
    Axis(
        name="fmri0_slice_timing",
        scope=SUBJECT,
        section=DIL.FMRI_0,
        option="slice_timing",
        values=_enum_values(SliceTiming, "UNKNOWN", "UP"),
        needs_input=DIL.FMRI_0,
    ),
    Axis(
        name="fmri1_slice_timing",
        scope=SUBJECT,
        section=DIL.FMRI_1,
        option="slice_timing",
        values=_enum_values(SliceTiming, "INTERLEAVED", "DOWN"),
        needs_input=DIL.FMRI_1,
    ),
    # Dummy-volume trimming is not an axis: it is baked into the phantom data.
    # fmri_0 carries real padding (subject.py trims it), fmri_1 carries none
    # (del=0 is then correct), so every pass loading both exercises "trim real
    # padding" and "correctly declare none" at once. No del_vols toggle.
    # ---- resting-state fMRI ---------------------------------------------------
    Axis(
        name="aroma",
        scope=SUBJECT,
        section=DIL.FMRI_RS,
        option="aroma",
        values=("false", "true"),
        gates={"true": "mni_templates"},
        needs_input=DIL.FMRI_RS,
    ),
    Axis(
        name="melodic_dim",
        scope=SUBJECT,
        section=DIL.FMRI_RS,
        option="melodic_dim",
        values=("0", "20"),
        needs_input=DIL.FMRI_RS,
        note="0 lets MELODIC estimate the dimensionality",
    ),
)

AXES_BY_NAME = {axis.name: axis for axis in AXES}


# --------------------------------------------------------------------------- #
# The passes
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class PassSpec:
    """One planned execution: which inputs to load, and how to configure them."""

    name: str
    description: str
    inputs: tuple  # DataInputList members to load
    values: dict  # axis name -> value
    #: recon-all is slow enough that it is opt-in (``--with-reconall``).
    heavy_freesurfer: bool = False


# T13D is the reference: every pass needs it.
_STRUCT = (
    DIL.T13D,
    DIL.FLAIR3D,
    DIL.MDC,
    DIL.FLAIR2D_TRA,
    DIL.FLAIR2D_COR,
    DIL.FLAIR2D_SAG,
    DIL.T2_COR,
)

PASSES = (
    PassSpec(
        name="structural_fsl",
        description=(
            "The whole structural family on the plain FSL backend: reference, "
            "3D FLAIR, MDC, the three 2D FLAIR planes, coronal T2, FLAT1, and "
            "the venous MR single-series shape."
        ),
        inputs=_STRUCT + (DIL.VENOUS_MR, DIL.SEEG_CT),
        values={
            "freesurfer_step": "DISABLED",
            "hippo_amyg_labels": "false",
            "synth_strip": "false",
            "registration_engine": "FSL",
            "synth_reconall": "false",
            "cuda": "false",
            "multicore_node_limit": "SOFT_CAP",
            "ref_bet_bias_correction": "false",
            "ref_bet_thr": "0.3",
            "flat1": "true",
            "venous_mr_shape": "single_series",
            "vein_detection_mode": "KURTOSIS",
            "venous_mr_bet_thr": "0.4",
            "electrode_threshold": "2000",
            "erode_kernel_size": "5",
        },
    ),
    # The ANTS counterpart of structural_fsl: the same structural family and the
    # same settings, differing only in the registration backend. ANTS is the
    # default engine, so many other passes run it implicitly by omitting the
    # axis; this pass forces it by name so the ANTS backend is a covered,
    # reviewable A/B pair against structural_fsl rather than riding on the
    # default. Phase 2 lifted the FLAT1/mni1 nonlinear pin and the seeg_ct CT
    # pin, so with flat1="true" and DIL.SEEG_CT loaded this pass now exercises
    # the ANTS *nonlinear* registration (composed boundary field into FLAT1)
    # and the ANTS seeg_ct cross-modality registration end to end, in addition
    # to the ANTS *linear* registrations it already covered.
    PassSpec(
        name="structural_ants",
        description=(
            "The whole structural family on the ANTs (antspyx) backend: the "
            "explicit ANTS twin of structural_fsl, forcing the linear and "
            "nonlinear registrations (FLAT1) and the seeg_ct cross-modality "
            "registration through antspyx instead of FLIRT/FNIRT."
        ),
        inputs=_STRUCT + (DIL.VENOUS_MR, DIL.SEEG_CT),
        values={
            "freesurfer_step": "DISABLED",
            "hippo_amyg_labels": "false",
            "synth_strip": "false",
            "registration_engine": "ANTS",
            "synth_reconall": "false",
            "cuda": "false",
            "multicore_node_limit": "SOFT_CAP",
            "ref_bet_bias_correction": "false",
            "ref_bet_thr": "0.3",
            "flat1": "true",
            "venous_mr_shape": "single_series",
            "vein_detection_mode": "KURTOSIS",
            "venous_mr_bet_thr": "0.4",
            "electrode_threshold": "2000",
            "erode_kernel_size": "5",
        },
    ),
    # The alternative *plain FSL* settings live in their own pass on purpose.
    # Folding them into the Synth pass would tie a dozen unrelated values to
    # the 14 GB SynthMorph requirement, so a modest box would silently lose
    # coverage of settings it is perfectly able to exercise.
    PassSpec(
        name="structural_alt_settings",
        description=(
            "The remaining structural preference values on the plain FSL "
            "backend: bias-corrected BET at a higher threshold, FLAT1 off, "
            "the two-series venous MR shape, tuned SEEG settings, hard core cap."
        ),
        inputs=(DIL.T13D, DIL.FLAIR3D, DIL.VENOUS_MR, DIL.SEEG_CT),
        values={
            "freesurfer_step": "DISABLED",
            "synth_strip": "false",
            "registration_engine": "FSL",
            "cuda": "false",
            "multicore_node_limit": "HARD_CAP",
            "ref_bet_bias_correction": "true",
            "ref_bet_thr": "0.5",
            "flat1": "false",
            "venous_mr_shape": "two_series",
            "vein_detection_mode": "SD",
            "venous_mr_bet_thr": "0.25",
            "electrode_threshold": "2500",
            "erode_kernel_size": "8",
        },
    ),
    # SynthStrip (5 GB) and SynthMorph (14 GB) are separate passes because
    # their RAM floors are far apart: a 12 GB box can run the first and not
    # the second, and must still get credit for the first.
    PassSpec(
        name="structural_synthstrip",
        description="Brain extraction through SynthStrip instead of BET.",
        inputs=(DIL.T13D, DIL.FLAIR3D),
        values={
            "freesurfer_step": "DISABLED",
            "synth_strip": "true",
            "registration_engine": "FSL",
            "cuda": "false",
        },
    ),
    PassSpec(
        name="structural_synthmorph",
        description=(
            "Registration through SynthMorph (and SynthStrip) instead of "
            "FLIRT/FNIRT. With FLAT1 on, this one pass drives SynthStrip in the "
            "reference deskull and SynthMorph in the linear (FLAIR->ref), FLAT1 "
            "and subject->MNI (mni1) nonlinear registrations."
        ),
        inputs=(DIL.T13D, DIL.FLAIR3D),
        values={
            "freesurfer_step": "DISABLED",
            "synth_strip": "true",
            "registration_engine": "SYNTH",
            "cuda": "false",
            # flat1 pulls in the nonlinear subject->MNI (mni1) path, so
            # SynthMorph is exercised on a nonlinear registration too, not only
            # the rigid FLAIR->reference one.
            "flat1": "true",
        },
    ),
    PassSpec(
        name="venous_ct_slicer",
        description=(
            "Venous CT through the Slicer-backed endocranium segmentation: "
            "both contrast-phase counts and both skull-threshold modes."
        ),
        inputs=(DIL.T13D, DIL.VENOUS_CT),
        values={
            "freesurfer_step": "DISABLED",
            "synth_strip": "false",
            "registration_engine": "FSL",
            "cuda": "false",
            "venous_ct_contrasts": "2",
            "skull_threshold": "-1",
            "multicore_node_limit": "SOFT_CAP",
        },
    ),
    # The ANTS counterpart of venous_ct_slicer: before Phase 2, venous_ct's
    # registration was FSL-pinned regardless of ``registration_engine``, so
    # leaving that axis unset here was harmless. Phase 2 routed venous_ct
    # through the engine-following abstraction (ANTS by default), which made
    # the unset axis silently ride the raw config default with NO capability
    # check at all (build_plan only gates/downgrades axes a pass explicitly
    # sets). Setting it explicitly puts it back under that gate: on a host
    # without antspyx it downgrades to FSL (recorded in item.downgrades)
    # instead of riding an unchecked default -- unlike structural_ants, a
    # downgrade here does not need a _PASS_REQUIREMENTS skip, since this pass
    # is not just an ANTS pin: it is also the only one exercising
    # venous_ct_contrasts=1 / skull_threshold=1500.
    PassSpec(
        name="venous_ct_fixed_threshold",
        description=(
            "Venous CT with a single contrast phase and a fixed skull "
            "threshold, forcing the ANTs backend -- the explicit ANTS twin "
            "of venous_ct_slicer's FSL registration."
        ),
        inputs=(DIL.T13D, DIL.VENOUS_CT),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "ANTS",
            "cuda": "false",
            "venous_ct_contrasts": "1",
            "skull_threshold": "1500",
        },
    ),
    PassSpec(
        name="func_map_synthseg",
        description=(
            "ASL and PET with the SynthSeg parcellation, to exercise the "
            "SynthSeg segmentation path (the asymmetry index is covered "
            "separately by func_map_no_freesurfer, since it does not depend "
            "on the FreeSurfer step)."
        ),
        inputs=(DIL.T13D, DIL.ASL, DIL.PET),
        values={
            "freesurfer_step": "SYNTHSEG",
            "synth_strip": "false",
            "registration_engine": "FSL",
            "cuda": "false",
            "asl_ai": "false",
            "pet_ai": "false",
            "multicore_node_limit": "SOFT_CAP",
        },
    ),
    # The asymmetry index lives here, not on func_map_synthseg: the symmetric
    # registration it needs is built from the reference alone
    # (MainWorkflow.ensure_sym_registration) and is independent of the
    # FreeSurfer step, so pinning AI to the SynthSeg pass (which needs 14 GB of
    # RAM) would leave AI untested on the default sweep of any host that cannot
    # run SynthSeg. Here it only needs the MNI templates and runs everywhere.
    PassSpec(
        name="func_map_no_freesurfer",
        description=(
            "ASL and PET without FreeSurfer, with the asymmetry index enabled "
            "(the symmetric-atlas registration path)."
        ),
        inputs=(DIL.T13D, DIL.ASL, DIL.PET),
        values={
            "freesurfer_step": "DISABLED",
            "cuda": "false",
            "asl_ai": "true",
            "pet_ai": "true",
        },
    ),
    # SynthMorph coverage for the functional-map registrations: func_map_workflow
    # feeds ASL/PET through get_registration_node(use_synth=morph), a path no
    # other pass exercises with synth on (func_map_synthseg keeps synth_morph
    # off). Requires the SynthMorph RAM floor, so it is skipped on smaller hosts.
    PassSpec(
        name="func_map_synthmorph",
        description="ASL and PET registered through SynthMorph instead of FLIRT/FNIRT.",
        inputs=(DIL.T13D, DIL.ASL, DIL.PET),
        values={
            "freesurfer_step": "DISABLED",
            "synth_strip": "true",
            "registration_engine": "SYNTH",
            "cuda": "false",
            "asl_ai": "false",
            "pet_ai": "false",
        },
    ),
    # Phase 3 lifted dti_preproc's FSL pin (it now follows registration_engine,
    # like the structural family), so this axis is pinned explicitly here to
    # keep this pass's documented FSL-baseline behaviour rather than silently
    # riding the (ANTS) default -- see structural_fsl/structural_ants.
    PassSpec(
        name="dti_classic",
        description=(
            "Diffusion on the CPU with the legacy eddy_correct and no "
            "tractography: the quick diffusion path."
        ),
        inputs=(DIL.T13D, DIL.DTI),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "FSL",
            "cuda": "false",
            "old_eddy_correct": "true",
            "tractography": "false",
            "multicore_node_limit": "NO_LIMIT",
        },
    ),
    # The CPU tractography baseline: modern eddy + BEDPOSTX + corticospinal
    # ProbTrackX, all on the CPU. It runs on every host that has the XTRACT
    # protocols, so the CPU path of that chain is always exercised. The GPU
    # variant below is the opt-in extra, gated by an actual GPU. Pinned FSL
    # (see dti_classic above); dti_tractography_ants below is its explicit ANTS
    # twin, exercising Phase 3's externalized probtrackx transforms (ROIs
    # warped MNI->ref->diff, diffusion-space probtrackx, diff->ref result warp)
    # end to end through antspyx.
    PassSpec(
        name="dti_tractography",
        description=(
            "Diffusion with the modern eddy, BEDPOSTX and corticospinal "
            "tractography on the CPU."
        ),
        inputs=(DIL.T13D, DIL.DTI),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "FSL",
            "cuda": "false",
            "old_eddy_correct": "false",
            "tractography": "true",
            "multicore_node_limit": "SOFT_CAP",
        },
    ),
    # The GPU counterpart: same chain with cuda=true. It requires a usable GPU
    # (see _PASS_REQUIREMENTS), so on a GPU-less host it is skipped and the CPU
    # baseline above is the only tractography pass; on a CUDA host both run and
    # the GPU and CPU paths of eddy/BEDPOSTX/ProbTrackX are both exercised.
    PassSpec(
        name="dti_tractography_gpu",
        description=(
            "The GPU path of the modern eddy / BEDPOSTX / corticospinal "
            "tractography chain, exercised only where the host has a usable GPU."
        ),
        inputs=(DIL.T13D, DIL.DTI),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "FSL",
            "cuda": "true",
            "old_eddy_correct": "false",
            "tractography": "true",
            "multicore_node_limit": "SOFT_CAP",
        },
    ),
    # The explicit ANTS twin of dti_tractography (Phase 3): the externalized
    # tractography path -- ROI MNI->ref->diff pre-warps, probtrackx run natively
    # in diffusion space (no xfm/inv_xfm), summed density warped diff->ref --
    # forced through antspyx instead of FLIRT/FNIRT, mirroring structural_ants.
    # Gated in _PASS_REQUIREMENTS: without antspyx it would downgrade to FSL and
    # exactly duplicate dti_tractography, so it is skipped instead.
    PassSpec(
        name="dti_tractography_ants",
        description=(
            "The ANTS backend twin of dti_tractography: externalized "
            "probtrackx transforms exercised end to end through antspyx "
            "instead of FLIRT/FNIRT."
        ),
        inputs=(DIL.T13D, DIL.DTI),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "ANTS",
            "cuda": "false",
            "old_eddy_correct": "false",
            "tractography": "true",
            "multicore_node_limit": "SOFT_CAP",
        },
    ),
    # SynthMorph/SynthStrip coverage for diffusion: dti_preproc_workflow uses
    # SynthStrip (b0 deskull) and SynthMorph (dif2ref / fa_2_ref), and
    # tractography_workflow uses SynthMorph for the tract registrations. No
    # other pass drives synth on the diffusion chain. Needs the SynthMorph RAM
    # floor, so it is skipped on smaller hosts. CPU only (cuda=false).
    PassSpec(
        name="dti_synthmorph",
        description=(
            "Diffusion (modern eddy, BEDPOSTX, corticospinal tractography) with "
            "SynthStrip/SynthMorph registration instead of FLIRT/FNIRT."
        ),
        inputs=(DIL.T13D, DIL.DTI),
        values={
            "freesurfer_step": "DISABLED",
            "synth_strip": "true",
            "registration_engine": "SYNTH",
            "cuda": "false",
            "old_eddy_correct": "false",
            "tractography": "true",
            "multicore_node_limit": "SOFT_CAP",
        },
    ),
    # Phase 3 lifted fMRI_preproc/task/resting_state's FSL pin (func->ref, and
    # the resting func->ref->mni concat, now follow registration_engine), so
    # this axis is pinned explicitly here to keep this pass's documented
    # FSL-baseline behaviour rather than silently riding the (ANTS) default --
    # see structural_fsl/structural_ants. fmri_task_and_rest_ants below is its
    # explicit ANTS twin.
    PassSpec(
        name="fmri_task_and_rest",
        description=(
            "Both task runs (rArA with dummy padding, rArBrArB without, "
            "different slice timings) plus resting state with MELODIC/ICA-AROMA."
        ),
        inputs=(DIL.T13D, DIL.FMRI_0, DIL.FMRI_1, DIL.FMRI_RS),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "FSL",
            "cuda": "false",
            "fmri0_block_design": "RARA",
            "fmri1_block_design": "RARB",
            "fmri0_slice_timing": "UNKNOWN",
            "fmri1_slice_timing": "INTERLEAVED",
            "aroma": "true",
            "melodic_dim": "0",
        },
    ),
    # The explicit ANTS twin of fmri_task_and_rest (Phase 3): func->ref (task
    # cluster applies, resting zstats apply) and the resting func->ref->mni
    # AROMA-branch concatenation (a stacked AntsApplyTransforms transformlist,
    # no ConvertWarp) forced through antspyx instead of FLIRT/FNIRT, mirroring
    # structural_ants. Gated in _PASS_REQUIREMENTS: without antspyx it would
    # downgrade to FSL and exactly duplicate fmri_task_and_rest, so it is
    # skipped instead.
    PassSpec(
        name="fmri_task_and_rest_ants",
        description=(
            "The ANTS backend twin of fmri_task_and_rest: EPI func->ref "
            "registration and the resting func->ref->mni concat exercised end "
            "to end through antspyx instead of FLIRT/FNIRT."
        ),
        inputs=(DIL.T13D, DIL.FMRI_0, DIL.FMRI_1, DIL.FMRI_RS),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "ANTS",
            "cuda": "false",
            "fmri0_block_design": "RARA",
            "fmri1_block_design": "RARB",
            "fmri0_slice_timing": "UNKNOWN",
            "fmri1_slice_timing": "INTERLEAVED",
            "aroma": "true",
            "melodic_dim": "0",
        },
    ),
    PassSpec(
        name="fmri_alt_settings",
        description=(
            "The remaining fMRI preference values: the other slice-timing "
            "modes, a fixed MELODIC dimensionality, AROMA off."
        ),
        inputs=(DIL.T13D, DIL.FMRI_0, DIL.FMRI_1, DIL.FMRI_RS),
        values={
            "freesurfer_step": "DISABLED",
            "registration_engine": "FSL",
            "cuda": "false",
            "fmri0_block_design": "RARA",
            "fmri1_block_design": "RARB",
            "fmri0_slice_timing": "UP",
            "fmri1_slice_timing": "DOWN",
            "aroma": "false",
            "melodic_dim": "20",
        },
    ),
    # SynthMorph/SynthStrip coverage for the venous MR chain: venous_mr_workflow
    # uses SynthStrip (deskull) and SynthMorph (vein registration to reference).
    # (Venous CT and SEEG CT deliberately stay on FLIRT, so they need no synth
    # pass.) Needs the SynthMorph RAM floor, so it is skipped on smaller hosts.
    PassSpec(
        name="venous_mr_synth",
        description="Venous MR through SynthStrip/SynthMorph instead of BET/FLIRT.",
        inputs=(DIL.T13D, DIL.VENOUS_MR),
        values={
            "freesurfer_step": "DISABLED",
            "synth_strip": "true",
            "registration_engine": "SYNTH",
            "cuda": "false",
            "venous_mr_shape": "single_series",
            "vein_detection_mode": "SD",
        },
    ),
    # ---- opt-in, slow --------------------------------------------------------
    PassSpec(
        name="freesurfer_autorecon_pial",
        description="FreeSurfer surfaces via autorecon-pial, feeding the ASL surface maps.",
        inputs=(DIL.T13D, DIL.ASL),
        values={
            "freesurfer_step": "AUTORECON_PIAL",
            "cuda": "false",
            "asl_ai": "false",
        },
        heavy_freesurfer=True,
    ),
    # The complete recon-all comes in two RAM/path modes, split into two passes
    # so a big host exercises BOTH rather than only the synth one:
    #   * freesurfer_reconall       -> classic recon-all (synth_reconall=false,
    #     ~5 GB, FS_V8_XOPTS=0). Runs on any FreeSurfer host (opt-in).
    #   * freesurfer_reconall_synth -> the FS v8 Synth-accelerated recon-all
    #     (synth_reconall=true, ~20 GB). Requires the synth_reconall RAM floor,
    #     so it is skipped on smaller hosts (see _PASS_REQUIREMENTS).
    # Splitting them (instead of letting one pass downgrade true->false) is the
    # same reasoning as the CPU/GPU tractography split: otherwise a 20 GB box
    # only ever tests the synth path and a smaller box only the classic one.
    PassSpec(
        name="freesurfer_reconall",
        description=(
            "The complete classic recon-all (lower RAM), with hippocampal/"
            "amygdala subfields and the asymmetry index."
        ),
        inputs=(DIL.T13D, DIL.ASL, DIL.PET),
        values={
            "freesurfer_step": "RECONALL",
            "hippo_amyg_labels": "true",
            "synth_reconall": "false",
            "cuda": "false",
            "asl_ai": "true",
            "pet_ai": "true",
        },
        heavy_freesurfer=True,
    ),
    PassSpec(
        name="freesurfer_reconall_synth",
        description=(
            "The complete recon-all on the FS v8 Synth-accelerated path "
            "(higher RAM), exercised only where the host has the ~20 GB it needs."
        ),
        inputs=(DIL.T13D, DIL.ASL, DIL.PET),
        values={
            "freesurfer_step": "RECONALL",
            "synth_reconall": "true",
            "cuda": "false",
            "asl_ai": "true",
            "pet_ai": "true",
        },
        heavy_freesurfer=True,
    ),
)


# --------------------------------------------------------------------------- #
# Resolution against the host
# --------------------------------------------------------------------------- #
@dataclass
class ResolvedPass:
    """A pass with every gated value resolved against the host capabilities."""

    spec: PassSpec
    values: dict  # axis name -> value actually used
    downgrades: list = field(default_factory=list)  # (axis, wanted, used, reason)
    skipped: bool = False
    skip_reason: str = ""

    @property
    def name(self) -> str:
        return self.spec.name

    @property
    def inputs(self) -> tuple:
        return self.spec.inputs


def _safe_value(axis: Axis, wanted, caps):
    """Return the first value of ``axis`` whose gate the host satisfies."""
    for candidate in (wanted,) + tuple(axis.values):
        gate = axis.gate_for(candidate)
        if not gate or caps.has(gate):
            return candidate, ""
    return None, "no usable value"


def build_plan(caps, with_reconall: bool = False, only=None) -> list:
    """Resolve every pass against the host, dropping or downgrading as needed.

    Parameters
    ----------
    caps : Capabilities
        The host probe.
    with_reconall : bool
        Include the slow FreeSurfer passes.
    only : iterable of str, optional
        Restrict to these pass names.
    """
    resolved = []
    for spec in PASSES:
        item = ResolvedPass(spec=spec, values=dict(spec.values))

        if only and spec.name not in only:
            continue
        if spec.heavy_freesurfer and not with_reconall:
            item.skipped = True
            item.skip_reason = "recon-all passes are opt-in (--with-reconall)"
            resolved.append(item)
            continue

        for axis_name, wanted in spec.values.items():
            axis = AXES_BY_NAME[axis_name]
            gate = axis.gate_for(wanted)
            if gate and not caps.has(gate):
                fallback, problem = _safe_value(axis, wanted, caps)
                if fallback is None or fallback == wanted:
                    item.skipped = True
                    item.skip_reason = "%s=%s needs %s: %s" % (
                        axis_name,
                        wanted,
                        gate,
                        caps.reason(gate),
                    )
                    break
                item.values[axis_name] = fallback
                item.downgrades.append((axis_name, wanted, fallback, caps.reason(gate)))

        # A pass whose whole reason for existing is now unavailable is skipped
        # rather than silently degraded into a duplicate of another pass.
        if not item.skipped:
            _skip_if_pointless(item, caps)
        resolved.append(item)

    return resolved


#: Passes that only make sense when a given capability is present. Public so the
#: plan-integrity test can grant every gating capability to its "capable host".
_PASS_REQUIREMENTS = {
    # Without antspyx the engine axis would silently downgrade ANTS->FSL (the
    # first ungated value), turning this pass into an undetected duplicate of
    # structural_fsl; gate it so it is skipped with a clear reason instead.
    "structural_ants": ("antspyx",),
    # Phase 3 ANTS twins of the EPI/diffusion baselines, same reasoning as
    # structural_ants: without antspyx the engine axis would silently
    # downgrade ANTS->FSL, exactly duplicating fmri_task_and_rest /
    # dti_tractography, so they are skipped with a clear reason instead.
    "fmri_task_and_rest_ants": ("antspyx",),
    "dti_tractography_ants": ("antspyx",),
    "structural_synthstrip": ("synth_strip",),
    "structural_synthmorph": ("synth_morph",),
    "func_map_synthmorph": ("synth_morph",),
    "venous_mr_synth": ("synth_morph",),
    "dti_synthmorph": ("synth_morph", "xtract"),
    "venous_ct_slicer": ("slicer",),
    "venous_ct_fixed_threshold": ("slicer",),
    # Matches the axis gate above: without synth_seg's RAM/version floor,
    # freesurfer_step would otherwise silently downgrade SYNTHSEG->DISABLED
    # (the first ungated axis value _safe_value finds), turning this pass into
    # an undetected duplicate of func_map_no_freesurfer instead of being
    # skipped with a clear reason.
    "func_map_synthseg": ("synth_seg",),
    "dti_tractography": ("xtract",),
    # The GPU pass needs both the protocols and an actual GPU; without one it
    # would only duplicate the CPU baseline, so it is skipped there.
    "dti_tractography_gpu": ("xtract", "cuda"),
    # recon-all passes lean on an -expert file in test_run, which an unpatched
    # FS 8.x recon-all crashes on (reconall_expert capability, false only on the
    # buggy build in test_run) -- gate them so they are skipped with a clear
    # "apply the patch" reason instead of failing hours in.
    "freesurfer_autorecon_pial": ("freesurfer", "reconall_expert"),
    "freesurfer_reconall": ("freesurfer", "reconall_expert"),
    # The synth recon-all needs its ~20 GB RAM floor; without it the classic
    # freesurfer_reconall pass already covers recon-all, so skip this one.
    "freesurfer_reconall_synth": ("synth_reconall", "reconall_expert"),
}


def _skip_if_pointless(item: ResolvedPass, caps) -> None:
    for capability in _PASS_REQUIREMENTS.get(item.name, ()):
        if not caps.has(capability):
            item.skipped = True
            item.skip_reason = "needs %s: %s" % (capability, caps.reason(capability))
            return


# --------------------------------------------------------------------------- #
# Coverage self-check
# --------------------------------------------------------------------------- #
@dataclass
class AxisCoverage:
    axis: Axis
    covered: dict = field(default_factory=dict)  # value -> [pass names]
    unreachable: dict = field(default_factory=dict)  # value -> reason
    deferred: dict = field(default_factory=dict)  # value -> reason a pass skipped

    @property
    def missing(self) -> list:
        """Values no pass sets at all — a genuine hole in the plan."""
        return [
            v
            for v in self.axis.values
            if v not in self.covered
            and v not in self.unreachable
            and v not in self.deferred
        ]


def coverage(plan: list, caps) -> dict:
    """Report, per axis, which values the plan exercises and which it does not.

    A value can be absent for three very different reasons, and conflating
    them would hide real bugs:

    * **unreachable** - the host cannot run it (missing capability, with the
      reason attached);
    * **deferred** - a pass *does* set it, but that pass was skipped in this
      run (typically the opt-in recon-all passes);
    * **missing** - no pass sets it anywhere. This one is a bug in the plan,
      and the only one worth failing over.
    """
    report = {axis.name: AxisCoverage(axis=axis) for axis in AXES}

    for axis in AXES:
        for value in axis.values:
            gate = axis.gate_for(value)
            if gate and not caps.has(gate):
                report[axis.name].unreachable[value] = "%s: %s" % (
                    gate,
                    caps.reason(gate),
                )

    def relevant(item, axis):
        # Only claim coverage if the pass actually loads the relevant input.
        return axis.needs_input is None or axis.needs_input in item.inputs

    # Running passes first: a value covered by any of them is covered, full
    # stop, even if some *other* (skipped) pass also happened to set it.
    for item in plan:
        if item.skipped:
            continue
        for axis_name, value in item.values.items():
            if relevant(item, AXES_BY_NAME[axis_name]):
                report[axis_name].covered.setdefault(value, []).append(item.name)

    for item in plan:
        if not item.skipped:
            continue
        for axis_name, value in item.values.items():
            entry = report[axis_name]
            if not relevant(item, AXES_BY_NAME[axis_name]):
                continue
            if value in entry.covered or value in entry.unreachable:
                continue
            entry.deferred.setdefault(value, item.skip_reason)

    return report


def describe_plan(plan: list, cover: dict) -> str:
    """A human summary of what will run, what will not, and why."""
    lines = []
    active = [p for p in plan if not p.skipped]
    lines.append(
        "Planned passes: %d to run, %d skipped" % (len(active), len(plan) - len(active))
    )
    for item in plan:
        if item.skipped:
            lines.append("  - %-28s SKIPPED  (%s)" % (item.name, item.skip_reason))
            continue
        inputs = ", ".join(str(i) for i in item.inputs)
        lines.append("  - %-28s %s" % (item.name, inputs))
        for axis_name, wanted, used, reason in item.downgrades:
            lines.append(
                "      downgraded %s: %s -> %s (%s)" % (axis_name, wanted, used, reason)
            )

    unreachable = {name: c.unreachable for name, c in cover.items() if c.unreachable}
    if unreachable:
        lines.append("Values this host cannot exercise:")
        for name, values in sorted(unreachable.items()):
            for value, reason in values.items():
                lines.append("  - %s=%s (%s)" % (name, value, reason))

    deferred = {name: c.deferred for name, c in cover.items() if c.deferred}
    if deferred:
        lines.append("Values deferred with a skipped pass:")
        for name, values in sorted(deferred.items()):
            for value, reason in values.items():
                lines.append("  - %s=%s (%s)" % (name, value, reason))

    holes = {name: c.missing for name, c in cover.items() if c.missing}
    if holes:
        lines.append("PLAN HOLES - no pass covers these values at all:")
        for name, values in sorted(holes.items()):
            lines.append("  - %s: %s" % (name, ", ".join(map(str, values))))
    else:
        lines.append("Coverage: every reachable axis value is exercised.")
    return "\n".join(lines)


def plan_holes(cover: dict) -> dict:
    """Axis values no pass covers anywhere — always a bug in :data:`PASSES`."""
    return {name: c.missing for name, c in cover.items() if c.missing}
